# Generated by Django 4.2.7 on 2025-10-21 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('date_of_birth', models.DateField(default='2002-7-23', verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('emergency_contact', models.JSONField(default=dict, help_text="{'name': 'الاسم', 'phone': 'رقم الهاتف', 'relation': 'العلاقة'}", verbose_name='جهة الاتصال في الطوارئ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'مرضى',
                'db_table': 'patients',
                'indexes': [models.Index(fields=['doctor', 'created_at'], name='patients_doctor__e97535_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_last_na_ce6411_idx')],
            },
        ),
    ]
