# Generated by Django 5.2.4 on 2025-10-23 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.JSONField(default=dict, verbose_name='جهة الاتصال في الطوارئ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية الوطنية'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='patients_nationa_c07601_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('doctor', 'national_id'), name='unique_patient_per_doctor'),
        ),
    ]
