# Generated by Django 4.2.7 on 2025-10-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=100, verbose_name='المادة المسببة للحساسية')),
                ('reaction', models.TextField(verbose_name='رد الفعل')),
                ('severity', models.CharField(choices=[('mild', 'خفيفة'), ('moderate', 'متوسطة'), ('severe', 'شديدة')], max_length=10, verbose_name='الخطورة')),
                ('onset_date', models.DateField(verbose_name='تاريخ الظهور')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساسية',
                'verbose_name_plural': 'حساسيات',
                'db_table': 'allergies',
                'ordering': ['-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('visit_type', models.CharField(choices=[('initial', 'زيارة أولى'), ('followup', 'متابعة'), ('emergency', 'طوارئ'), ('consultation', 'استشارة')], max_length=50, verbose_name='نوع الزيارة')),
                ('blood_pressure', models.CharField(blank=True, max_length=10, verbose_name='ضغط الدم')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='معدل ضربات القلب')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='درجة الحرارة')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='الطول (م)')),
                ('chief_complaint', models.TextField(verbose_name='الشكوى الرئيسية')),
                ('physical_exam', models.TextField(blank=True, verbose_name='الفحص البدني')),
                ('assessment', models.TextField(blank=True, verbose_name='التشخيص')),
                ('plan', models.TextField(blank=True, verbose_name='الخطة')),
                ('lab_results', models.JSONField(default=dict, verbose_name='نتائج المختبر')),
                ('imaging_results', models.JSONField(default=dict, verbose_name='نتائج الأشعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تاريخ مرضي',
                'verbose_name_plural': 'تواريخ مرضية',
                'db_table': 'medical_histories',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancer_type', models.CharField(choices=[('breast', 'سرطان الثدي'), ('lung', 'سرطان الرئة'), ('colon', 'سرطان القولون'), ('prostate', 'سرطان البروستاتا'), ('leukemia', 'سرطان الدم (لوكيميا)'), ('lymphoma', 'لمفوما'), ('melanoma', 'ميلانوما'), ('pancreatic', 'سرطان البنكرياس'), ('liver', 'سرطان الكبد'), ('brain', 'سرطان الدماغ'), ('other', 'أخرى')], max_length=50, verbose_name='نوع السرطان')),
                ('cancer_subtype', models.CharField(blank=True, max_length=100, verbose_name='النوع الفرعي')),
                ('cancer_stage', models.CharField(choices=[('0', 'المرحلة 0'), ('I', 'المرحلة I'), ('II', 'المرحلة II'), ('III', 'المرحلة III'), ('IV', 'المرحلة IV'), ('unknown', 'غير معروف')], max_length=10, verbose_name='مرحلة السرطان')),
                ('diagnosis_date', models.DateField(verbose_name='تاريخ التشخيص')),
                ('diagnosis_details', models.TextField(blank=True, verbose_name='تفاصيل التشخيص')),
                ('symptoms', models.JSONField(default=list, verbose_name='الأعراض')),
                ('comorbidities', models.JSONField(default=list, verbose_name='الأمراض المصاحبة')),
                ('family_history', models.TextField(blank=True, verbose_name='التاريخ العائلي')),
                ('initial_treatment_plan', models.TextField(blank=True, verbose_name='الخطة العلاجية الأولية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل طبي',
                'verbose_name_plural': 'سجلات طبية',
                'db_table': 'medical_records',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patients_is_acti_4a96f9_idx'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient'),
        ),
    ]
